### ISSUE TITLE
Stateless component 並不提升運行效率

### ISSUE THREAD

**Issue by abbychau** [noootown/book-deeperience-react-native#1]
很謝謝你們的boilerplate, 寫得很好, 也解釋了很多細節

但在這一頁中: https://noootown.gitbooks.io/deeperience-react-native-boilerplate/content/Basic/Reactjs%20Lifecycle%20&%20State%20vs%20Props.html

說到

> 寫成 stateless component 的好處主要有兩個
> 效率好
> 易讀

而實際上設計成stateless 和stateful 並不影響運行效率
具體原因可以看看 https://medium.com/modus-create-front-end-development/component-rendering-performance-in-react-df859b474adc

但如果是想說維護效率或者開發效率的話, 刻意寫出會比較好

**Comment by noootown** [comment]
OKOK，我了解了，謝謝你：）
